// Mapa de temas de cor por acento. As strings de classe são escritas por
// extenso (não concatenadas) para que o Tailwind as detecte e gere.
// Cada tema traz também os HEX usados nas capas SVG (CoverArt).

export const THEMES = {
  coral: {
    chip: "bg-coral-100 text-coral-700",
    text: "text-coral-600",
    softBg: "bg-coral-50",
    iconWrap: "bg-coral-100 text-coral-600",
    solid: "bg-coral-500 hover:bg-coral-600",
    border: "border-coral-200",
    ring: "ring-coral-200",
    dot: "text-coral-200",
    glow: "shadow-coral",
    from: "#FF8A6B",
    to: "#FF5277",
    accent: "#FFD15C",
    deep: "#B23A4A",
  },
  lilac: {
    chip: "bg-lilac-100 text-lilac-700",
    text: "text-lilac-600",
    softBg: "bg-lilac-50",
    iconWrap: "bg-lilac-100 text-lilac-600",
    solid: "bg-lilac-500 hover:bg-lilac-600",
    border: "border-lilac-200",
    ring: "ring-lilac-200",
    dot: "text-lilac-200",
    glow: "shadow-lilac",
    from: "#A78BFA",
    to: "#7C3AED",
    accent: "#FFD15C",
    deep: "#5B2A9E",
  },
  sunny: {
    chip: "bg-sunny-200 text-sunny-600",
    text: "text-sunny-600",
    softBg: "bg-sunny-100",
    iconWrap: "bg-sunny-200 text-sunny-600",
    solid: "bg-sunny-500 hover:bg-sunny-600",
    border: "border-sunny-300",
    ring: "ring-sunny-300",
    dot: "text-sunny-300",
    glow: "shadow-soft",
    from: "#FFD66B",
    to: "#FF9E40",
    accent: "#FF6B6B",
    deep: "#C77A1E",
  },
  mint: {
    chip: "bg-mint-100 text-mint-600",
    text: "text-mint-600",
    softBg: "bg-mint-100",
    iconWrap: "bg-mint-100 text-mint-600",
    solid: "bg-mint-500 hover:bg-mint-600",
    border: "border-mint-300",
    ring: "ring-mint-300",
    dot: "text-mint-300",
    glow: "shadow-soft",
    from: "#5FE0D1",
    to: "#1FA89B",
    accent: "#FFD15C",
    deep: "#15776E",
  },
  sky: {
    chip: "bg-sky-100 text-sky-700",
    text: "text-sky-700",
    softBg: "bg-sky-50",
    iconWrap: "bg-sky-100 text-sky-700",
    solid: "bg-sky-500 hover:bg-sky-600",
    border: "border-sky-200",
    ring: "ring-sky-200",
    dot: "text-sky-200",
    glow: "shadow-soft",
    from: "#7FBDF8",
    to: "#4F86E0",
    accent: "#FFD15C",
    deep: "#2E5BA8",
  },
}

export const themeOf = (key) => THEMES[key] ?? THEMES.coral
